export const SCORE_UP = "SCORE_UP";
export const SCORE_UP_ASYNC = "SCORE_UP_ASYNC";
export const SCORE_DOWN = "SCORE_DOWN";
export const SCORE_DOWN_ASYNC = "SCORE_DOWN_ASYNC";

//creator post req
export const TEST_ASYNC_REQ = "TEST_ASYNC_REQ";
//creator post res인데 execute에 실패 성공 횟우 말해준다
export const TEST_ASYNC_RES = "TEST_ASYNC_RES";

export const LIST_DAG_REQ = "LIST_DAG_REQ";
export const LIST_DAG_RES = "LIST_DAG_RES";

export const UPDATE_DAG_REQ = "UPDATE_DAG_REQ";
export const UPDATE_DAG_RES = "UPDATE_DAG_RES";


//execution success failed ....
export const STATE_SUCCESS_REQ = "STATE_SUCCESS_REQ";
export const STATE_SUCCESS_RES = "STATE_SUCCESS_RES";
export const STATE_FAILED_REQ = "STATE_FAILED_REQ";
export const STATE_FAILED_RES = "STATE_FAILED_RES";

//dag run post
export const POST_DAGRUN_REQ = "POST_DAGRUN_REQ";
export const POST_DAGRUN_RES = "POST_DAGRUN_RES";


export const CRON_VALUE_REQ = "CRON_VALUE_REQ";
export const CRON_VALUE_RES = "CRON_VALUE_RES";

export const PATH_MESSAGE_REQ = "PATH_MESSAGE_REQ";

export const PATH_VALUE_REQ="PATH_VALUE_REQ";

export const SOURCE_DETAIL_REQ="SOURCE_DETAIL_REQ";

//SFTP CONNECTION
export const CONNECTION_ID_REQ = "CONNECTION_ID_REQ";
export const CONNECTION_NAME_REQ = "CONNECTION_NAME_REQ";
export const CONNECTION_ID_MESSAGE_REQ = "CONNECTION_ID_MESSAGE_REQ";
export const CONNECTION_NAME_MESSAGE_REQ = "CONNECTION_NAME_MESSAGE_REQ";

//DB CONNECTION
export const CONNECTION_DBID_REQ = "CONNECTION_DBID_REQ";
export const CONNECTION_DBNAME__REQ = "CONNECTION_DBNAME__REQ";
export const CONNECTION_DBID_MESSAGE_REQ = "CONNECTION_DBID_MESSAGE_REQ";
export const CONNECTION_DBNAME_MESSAGE_REQ = "CONNECTION_DBNAME_MESSAGE_REQ";


export const CONNECTION_DB_REQ = "CONNECTION_DB_REQ";
export const CONNECTION_FILE_REQ = "CONNECTION_FILE_REQ";
export const SOURCENAME_CHECK_REQ = "SOURCENAME_CHECK_REQ";
export const TARGETNAME_CHECK_REQ = "TARGETNAME_CHECK_REQ";
export const CONNECTION_TEST_REQ = "CONNECTION_TEST_REQ";
export const CONNECTION_MESSAGE_REQ = "CONNECTION_MESSAGE_REQ";

export const SFTPCONNECTION_REQ = "FILECONNECTION_REQ";
export const SFTPCONNECTION_MESSAGE_REQ = "FILECONNECTION_MESSAGE_REQ";

export const TARGETNAME_REQ = "TARGETNAME_REQ";
export const TARGETNAMEVALUE_REQ = "TARGETNAMEVALUE_REQ";
export const TARGETCONID_REQ = "TARGETCONID_REQ";

export const SOURCEID_REQ = "SOURCEID_REQ";
export const TARGETID_REQ = "TARGETID_REQ";
export const FILE_TYPE_LIST_REQ = "FILE_TYPE_LIST_REQ";

export const DBCONNECTION_ID_REQ = "DBCONNECTION_ID_REQ";

//
export const DAGCREATE_TRANSTYPE_REQ = "DAGCREATE_TRANSTYPE_REQ";
export const DAGCREATE_SAVEMODE_REQ = "DAGCREATE_SAVEMODE_REQ";
export const DAGCREATE_TARGETLOCATION_REQ = "DAGCREATE_TARGETLOCATION_REQ";
export const DAGCREATE_TARGETCONNID_REQ = "DAGCREATE_TARGECONNID_REQ";


export const DAGCREATE_DBMSTYPE_REQ = "DAGCREATE_DBMSTYPE_REQ";

export const SENSOR_ID_REQ = "SENSOR_ID_REQ";

export const TASK_SENSORID_REQ = "TASK_SENSORID_REQ";

export const LOG_DAGRUNID_REQ = "LOG_DAGRUNID_REQ";
export const LOG_SENSORID_REQ = "LOG_SENSORID_REQ";
export const LOG_TASK_REQ = "LOG_TASK_REQ";

export const LOG_FLOW_ID = "LOG_FLOW_ID";
export const LOG_TRYNUMBER_REQ="LOG_TRYNUMBER_REQ";

//UPDATE
export const TARGET_NAME_REQ = "TARGET_NAME_REQ";
export const TARGET_LOCATION_REQ  = "TARGET_LOCATION_REQ";
export const TARGET_SAVEMODE_REQ = "TARGET_SAVEMODE_REQ";
export const TARGET_ID_REQ = "TARGET_ID_REQ";
export const TARGET_CONNID_REQ = "TARGET_CONNID_REQ";


export const SOURCE_ID_REQ = "SOURCE_ID_REQ";
export const SOURCE_DB_CONNID_REQ = "SOURCE_DB_CONNID_REQ";
export const SOURCE_NAME_REQ ="SOURCE_NAME_REQ";
export const SOURCE_LOCALPATH_REQ = "SOURCE_LOCALPATH_REQ";
export const SOURCE_DBMSTYPE_REQ = "SOURCE_DBMSTYPE_REQ";


//DBCreate db_conn_id ex) {id : 5}
export const SOURCE_DB_CONNECTION_ID = "SOURCE_DB_CONNECTION_ID";

//fileflow file_name
export const FLOW_FILENAME_REQ = "FLOW_FILENAME_REQ";

//SFTP RESULT MSG
export const SFTP_RESULT_MSG_REQ = "SFTP_RESULT_MSG_REQ";

export const FLOW_ISPAUSED_REQ = "FLOW_ISPAUSED_REQ";

//FlowWidget sensor_id ,id
export const FLOWWIDGET_SENSORID_REQ="FLOWWIDGET_SENSORID_REQ";
export const FLOWWIDGET_ID_REQ="FLOWWIDGET_ID_REQ";

//SourceWidget Sourcename
export const SOURCEWIDGET_NAME_REQ = "SOURCEWIDGET_NAME_REQ";

//TargetWidget Targetname
export const TARGETWIDGET_NAME_REQ = "TARGETWIDGET_NAME_REQ";


export const IMPORTERROR_REQ = "IMPORTERROR_REQ";
